
title: My anuree
url: 'http://anuree.github.io'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: anuree  ## put your name
title: 'anuree &game; ## your title
location: Ubon


## Social Profiles
facebook: May Nai ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
